"""Bug_fixed

Revision ID: 1fc890d64ba5
Revises: 674f79c04f42
Create Date: 2023-04-05 22:37:18.018026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fc890d64ba5'
down_revision = '674f79c04f42'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
