"""Added_user_api_key

Revision ID: 674f79c04f42
Revises: 45dedf4c28b5
Create Date: 2023-04-05 21:05:30.519152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '674f79c04f42'
down_revision = '45dedf4c28b5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('custom_key', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('user_openai_key', sa.TEXT(), nullable=True))
    op.add_column('users', sa.Column('user_openai_max_tokens', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_openai_max_tokens')
    op.drop_column('users', 'user_openai_key')
    op.drop_column('users', 'custom_key')
    # ### end Alembic commands ###
